version: "2.4"
services:
  api:
    image: acme.com/applications:dev
    build:
      context: .
      dockerfile: applications-api/Dockerfile
    ports:
      - 5000:5000
    healthcheck:
      test: curl --fail http://localhost:5000/health || exit -1
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  outsidein:
    image: acme.com/applications-outsideintests:dev
    build:
      context: .
      dockerfile: OutsideInTests/Dockerfile
    environment: 
      API_HOST: api
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      api:
        condition: service_healthy