version: "2.4"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Top-Secret
      MSSQL_PID: Developer

  api:
    image: acme.com/applications:0.1
    build:
      context: .
      dockerfile: applications-api/Dockerfile
    ports:
      - 5000:5000

  flaky-service:
    image: sample.com/flaky-service:1.0
    build:
      context: .
      dockerfile: flaky-service/Dockerfile
